---
- hosts: localhost
  become: yes
  become_method: sudo
  vars_files: 
  - some_region.yaml
  tasks:  
  - name: Install Package
    package:
      name: "{{package_name}}"
      state: "{{latest}}"