---
- name: ec2 instance
  hosts: localhost
  connection: local
  tasks:
  - name: Launch EC2
    ec2:
      instance type: t2.micro
      key name: createdbytower
      image: ami-0affd4508a5d2481b
      region: us-west-2
      group: default
      count: 2
      vpc-subnet-id: subnet-09bf1d24f2a8fec27
      wait: yes
      assign_public_ip: yes 