---
- name: ec2 instance
  hosts: localhost
  connection: local
  tasks:
  - name: Launch EC2
    ec2:
      instance_type: t2.micro
      key_name: bastion
      image: ami-01a6e31ac994bbc09
      region: eu-west-2
      group: default
      count: 2
      vpc-subnet-id: subnet-016eea02c2119e2cc
      wait: yes
      assign_public_ip: yes 